security:
    # Configure password hashing for users
    password_hashers:
        App\Entity\User: auto  # Hash passwords using the latest algorithm

    # Define how to load users
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User  # Use the User entity
                property: email          # Load users by email

    firewalls:
        # Disable security for dev routes (profiler, debug toolbar, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall configuration for authentication and session management
        main:
            lazy: true  # Enables on-demand firewall initialization
            provider: app_user_provider  # Use our user provider

            # Enable form-based login
            form_login:
                login_path: app_login         # Route to the login form
                check_path: login_check       # Route for login submission
                default_target_path: app_home # Redirect after login (default)

            # Enable logout handling
            logout:
                path: app_logout              # Route to trigger logout
                target: app_login             # Redirect after logout

            # Enable "remember me" functionality (optional)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 1 week in seconds
                path: /

    # Define access control for different roles and routes
    access_control:
        - { path: ^/proprietaire, roles: ROLE_PROPRIETAIRE }  # ProprietaireSalle access
        - { path: ^/client, roles: ROLE_CLIENT }              # Client access
        - { path: ^/admin, roles: ROLE_ADMIN }                # Admin access

    # Optional: Define role inheritance
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_PROPRIETAIRE: [ROLE_USER]
        ROLE_CLIENT: [ROLE_USER]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4         # For bcrypt: lowest cost
                time_cost: 3     # For Argon2id: lowest time cost
                memory_cost: 10  # For Argon2id: lowest memory cost
