security:
    # Configure password hashing for users
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto  # Use the latest algorithm

    # Define how to load users
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User  # Specify the User entity
                property: email          # Authenticate users by email

    firewalls:
        # Disable security for dev routes (profiler, debug toolbar, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall for authentication and session management
        main:
            pattern: ^/  # Match all routes by default
            lazy: true  # Delay firewall activation until needed
            provider: app_user_provider  # Use our custom user provider

            # Enable form-based login
            form_login:
                login_path: app_login           # Route for displaying login form
                check_path: login_check         # Route for form submission check
                default_target_path: app_home   # Redirect after successful login

            # Logout configuration
            logout:
                path: app_logout               # Route to trigger logout
                target: app_login              # Redirect after logout

            # Enable "remember me" functionality (optional)
            remember_me:
                secret: '%kernel.secret%'      # Secret used for cookies
                lifetime: 604800  # 1 week (in seconds)
                path: /

            # Allow requests from unauthenticated users (default behavior)
            stateless: false

    # Access control rules for different routes and roles
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    # Role hierarchy to simplify permissions management
    role_hierarchy:
        ROLE_ADMIN: [ROLE_PROPRIETAIRE, ROLE_CLIENT, ROLE_USER]
        ROLE_PROPRIETAIRE: [ROLE_USER]
        ROLE_CLIENT: [ROLE_USER]

when@test:
    # Weaken password hashing for tests to speed things up
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4         # Lowest cost for bcrypt
                time_cost: 3     # Lowest time cost for Argon2id
                memory_cost: 10  # Lowest memory cost for Argon2id
