security:
    # Configure password hashing for users
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto  # Use the latest algorithm

    # Define how to load users
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User  # Specify the User entity
                property: email          # Authenticate users by email

    firewalls:
        # Disable security for dev routes (profiler, debug toolbar, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall for authentication and session management
        main:
            pattern: ^/  # Match all routes by default
            lazy: true  # Delay firewall activation until needed
            provider: app_user_provider  # Use our custom user provider
            custom_authenticator: App\Security\UserAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

            
    # Access control rules for different routes and roles

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    # Role hierarchy to simplify permissions management
    role_hierarchy:
        ROLE_ADMIN: [ROLE_CLIENT, ROLE_USER]
        ROLE_PROPRIETAIRE: [ROLE_PROPRIETAIRE]
        ROLE_CLIENT: [ROLE_USER]

when@test:
    # Weaken password hashing for tests to speed things up
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4         # Lowest cost for bcrypt
                time_cost: 3     # Lowest time cost for Argon2id
                memory_cost: 10  # Lowest memory cost for Argon2id
